import React, { useEffect, useState } from 'react';
import DashboardLayout from '../../components/DashboardLayout';
import { patientApi } from '../../api/patient';
import { FileText, Stethoscope, Pill, Calendar, Clock, ChevronDown, ChevronUp, Download } from 'lucide-react';
import { format } from 'date-fns';
import { toast } from 'react-hot-toast';
import { SkeletonCard } from '../../components/ui/Skeleton';
import { pdf, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

// ── PDF Styles ──
const pdfStyles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#1e293b' },
  header: { marginBottom: 20, borderBottom: '2px solid #059669', paddingBottom: 12 },
  title: { fontSize: 20, fontWeight: 'bold', color: '#059669' },
  subtitle: { fontSize: 11, color: '#64748b', marginTop: 2 },
  section: { marginTop: 16 },
  sectionTitle: { fontSize: 11, fontWeight: 'bold', color: '#334155', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  label: { color: '#64748b', width: '35%' },
  value: { color: '#1e293b', width: '65%', fontWeight: 'bold' },
  box: { backgroundColor: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: 4, padding: 10, marginTop: 8 },
  medRow: { flexDirection: 'row', borderBottom: '1px solid #e2e8f0', paddingVertical: 4 },
  medCell: { flex: 1, paddingRight: 4 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', color: '#94a3b8', fontSize: 8 },
  invoiceAmount: { fontSize: 24, fontWeight: 'bold', color: '#059669', textAlign: 'center', marginTop: 10 },
  badge: { backgroundColor: '#dcfce7', color: '#166534', padding: '3 8', borderRadius: 4, fontSize: 9, alignSelf: 'flex-start' },
});

// ── Prescription PDF Document ──
const PrescriptionPDF = ({ record }) => {
  let meds = record.medications;
  if (typeof meds === 'string') { try { meds = JSON.parse(meds); } catch { meds = []; } }
  if (!Array.isArray(meds)) meds = [];

  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        <View style={pdfStyles.header}>
          <Text style={pdfStyles.title}>MedPortal · Prescription</Text>
          <Text style={pdfStyles.subtitle}>
            {format(new Date(record.appointment_date), 'MMMM d, yyyy')} · {record.slot_time?.substring(0, 5)}
          </Text>
        </View>

        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>Doctor</Text>
          <View style={pdfStyles.row}>
            <Text style={pdfStyles.label}>Name</Text>
            <Text style={pdfStyles.value}>Dr. {record.doctor_first_name} {record.doctor_last_name}</Text>
          </View>
          <View style={pdfStyles.row}>
            <Text style={pdfStyles.label}>Specialisation</Text>
            <Text style={pdfStyles.value}>{record.doctor_specialisation || 'N/A'}</Text>
          </View>
        </View>

        {record.prescription_notes && (
          <View style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>Clinical Notes</Text>
            <View style={pdfStyles.box}>
              <Text>{record.prescription_notes}</Text>
            </View>
          </View>
        )}

        {meds.length > 0 && (
          <View style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>Prescribed Medications</Text>
            <View style={{ ...pdfStyles.medRow, borderBottom: '2px solid #059669' }}>
              {['Medication', 'Dosage', 'Frequency', 'Duration'].map((h) => (
                <View key={h} style={pdfStyles.medCell}><Text style={{ fontWeight: 'bold', color: '#059669' }}>{h}</Text></View>
              ))}
            </View>
            {meds.filter(Boolean).map((med, i) => (
              <View key={i} style={pdfStyles.medRow}>
                <View style={pdfStyles.medCell}><Text>{med.medication_name}</Text></View>
                <View style={pdfStyles.medCell}><Text>{med.dosage}</Text></View>
                <View style={pdfStyles.medCell}><Text>{med.frequency}</Text></View>
                <View style={pdfStyles.medCell}><Text>{med.duration_days} days</Text></View>
              </View>
            ))}
          </View>
        )}

        {record.patient_friendly_summary && (
          <View style={pdfStyles.section}>
            <Text style={pdfStyles.sectionTitle}>AI Patient Summary</Text>
            <View style={pdfStyles.box}>
              <Text>{record.patient_friendly_summary}</Text>
            </View>
          </View>
        )}

        <Text style={pdfStyles.footer}>
          Generated by MedPortal · This is a digital prescription. Please consult your doctor for any questions.
        </Text>
      </Page>
    </Document>
  );
};

// ── Invoice PDF Document ──
const InvoicePDF = ({ record, payment }) => (
  <Document>
    <Page size="A4" style={pdfStyles.page}>
      <View style={pdfStyles.header}>
        <Text style={pdfStyles.title}>MedPortal · Invoice</Text>
        <Text style={pdfStyles.subtitle}>Receipt for consultation payment</Text>
      </View>

      <View style={pdfStyles.section}>
        <Text style={pdfStyles.sectionTitle}>Service Details</Text>
        <View style={pdfStyles.row}>
          <Text style={pdfStyles.label}>Service</Text>
          <Text style={pdfStyles.value}>Medical Consultation</Text>
        </View>
        <View style={pdfStyles.row}>
          <Text style={pdfStyles.label}>Doctor</Text>
          <Text style={pdfStyles.value}>Dr. {record.doctor_first_name} {record.doctor_last_name}</Text>
        </View>
        <View style={pdfStyles.row}>
          <Text style={pdfStyles.label}>Date</Text>
          <Text style={pdfStyles.value}>{format(new Date(record.appointment_date), 'MMMM d, yyyy')} at {record.slot_time?.substring(0, 5)}</Text>
        </View>
        <View style={pdfStyles.row}>
          <Text style={pdfStyles.label}>Status</Text>
          <Text style={pdfStyles.value}>Completed</Text>
        </View>
      </View>

      <View style={{ ...pdfStyles.section, ...pdfStyles.box, alignItems: 'center' }}>
        <Text style={pdfStyles.sectionTitle}>Amount Paid</Text>
        {payment ? (
          <Text style={pdfStyles.invoiceAmount}>
            {payment.currency} {payment.amountPaid?.toFixed(2)}
          </Text>
        ) : (
          <Text style={pdfStyles.invoiceAmount}>On File</Text>
        )}
        <Text style={pdfStyles.badge}>PAID</Text>
      </View>

      <Text style={pdfStyles.footer}>
        Generated by MedPortal · Powered by Stripe · Thank you for using our service.
      </Text>
    </Page>
  </Document>
);

// ── PDF Download Helper ──
const downloadPdf = async (docComponent, filename) => {
  try {
    const blob = await pdf(docComponent).toBlob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  } catch (err) {
    console.error('PDF generation failed:', err);
    toast.error('Could not generate PDF. Please try again.');
  }
};


const AppointmentHistory = () => {
  const [history, setHistory] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');
  const [expandedId, setExpandedId] = useState(null);

  const navigation = [
    { name: 'Dashboard', href: '/patient/dashboard' },
    { name: 'Search Doctors', href: '/patient/doctors' },
    { name: 'Appointment History', href: '/patient/history' },
  ];

  useEffect(() => {
    const fetchHistory = async () => {
      try {
        const profileRes = await patientApi.getPatientProfile();
        const patientId = profileRes.data.data.id;
        
        const historyRes = await patientApi.getPatientHistory(patientId);
        setHistory(historyRes.data.data || []);
      } catch {
        toast.error('Failed to load history');
        setError('Failed to load history.');
      } finally {
        setIsLoading(false);
      }
    };
    fetchHistory();
  }, []);

  const toggleExpand = (id) => {
    setExpandedId(expandedId === id ? null : id);
  };

  return (
    <DashboardLayout title="Patient Portal" roleColor="emerald" navigation={navigation}>
      <div className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Medical History</h2>
        <p className="mt-1 text-sm text-gray-500">
          Review your past appointments, doctor's notes, prescriptions, and AI summaries.
        </p>
      </div>

      {isLoading ? (
        <div className="space-y-6">
          <SkeletonCard />
          <SkeletonCard />
        </div>
      ) : error ? (
        <div className="bg-red-50 p-4 rounded-md">
          <p className="text-sm text-red-700">{error}</p>
        </div>
      ) : history.length === 0 ? (
        <div className="text-center py-12 bg-white rounded-lg border border-gray-200 shadow-sm">
          <FileText className="mx-auto h-12 w-12 text-gray-300" />
          <h3 className="mt-2 text-sm font-medium text-gray-900">No history found</h3>
          <p className="mt-1 text-sm text-gray-500">You don't have any past appointments yet.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {history.map((record) => {
            const isExpanded = expandedId === record.appointment_id;
            const dateObj = new Date(record.appointment_date);
            
            return (
              <div key={record.appointment_id} className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
                <div 
                  className="px-6 py-4 flex items-center justify-between cursor-pointer hover:bg-gray-50 transition-colors"
                  onClick={() => toggleExpand(record.appointment_id)}
                >
                  <div className="flex items-center space-x-4">
                    <div className="bg-emerald-100 p-3 rounded-full">
                      <Stethoscope className="h-6 w-6 text-emerald-600" />
                    </div>
                    <div>
                      <h4 className="text-lg font-bold text-gray-900">Dr. {record.doctor_first_name} {record.doctor_last_name}</h4>
                      <div className="flex items-center text-sm text-gray-500 space-x-4 mt-1">
                        <span className="flex items-center"><Calendar className="h-4 w-4 mr-1" /> {format(dateObj, 'MMMM d, yyyy')}</span>
                        {record.slot_time && (
                          <span className="flex items-center"><Clock className="h-4 w-4 mr-1" /> {record.slot_time.substring(0, 5)}</span>
                        )}
                        <span className="capitalize flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
                          {record.status}
                        </span>
                      </div>
                    </div>
                  </div>
                  <div>
                    {isExpanded ? <ChevronUp className="h-5 w-5 text-gray-400" /> : <ChevronDown className="h-5 w-5 text-gray-400" />}
                  </div>
                </div>

                {isExpanded && (
                  <div className="px-6 py-5 border-t border-gray-200 bg-gray-50">
                    <div className="grid md:grid-cols-2 gap-6">
                      
                      {/* Left Column */}
                      <div className="space-y-6">
                        {record.raw_symptoms && (
                          <div>
                            <h5 className="text-sm font-medium text-gray-900 mb-2 flex items-center">
                              <span className="w-2 h-2 bg-emerald-400 rounded-full mr-2"></span>
                              Symptoms Reported
                            </h5>
                            <p className="text-sm text-gray-700 bg-white p-3 rounded border border-gray-200">
                              {record.raw_symptoms}
                            </p>
                          </div>
                        )}

                        {record.patient_friendly_summary && (
                          <div>
                            <h5 className="text-sm font-medium text-gray-900 mb-2 flex items-center">
                              <span className="w-2 h-2 bg-blue-400 rounded-full mr-2"></span>
                              AI Summary
                            </h5>
                            <div className="text-sm text-gray-700 bg-blue-50 p-4 rounded-lg border border-blue-100 prose prose-sm max-w-none">
                              {record.patient_friendly_summary.split('\n').map((line, idx) => (
                                <p key={idx} className="mb-2 last:mb-0">{line}</p>
                              ))}
                            </div>
                          </div>
                        )}
                      </div>

                      {/* Right Column */}
                      <div>
                        {record.prescription_notes ? (
                          <div>
                            <h5 className="text-sm font-medium text-gray-900 mb-2 flex items-center">
                              <Pill className="h-4 w-4 mr-2 text-emerald-600" />
                              Prescription & Doctor's Notes
                            </h5>
                            <div className="text-sm text-gray-700 bg-white p-4 rounded-lg border border-emerald-100 shadow-inner whitespace-pre-wrap">
                              <p>{record.prescription_notes}</p>
                              {(() => {
                                let meds = record.medications;
                                if (typeof meds === 'string') {
                                  try { meds = JSON.parse(meds); } catch { meds = []; }
                                }
                                if (meds && Array.isArray(meds) && meds.length > 0 && meds[0] !== null) {
                                  return (
                                    <div className="mt-4 border-t border-emerald-100 pt-4">
                                      <h6 className="font-semibold text-emerald-800 mb-2">Prescribed Medications:</h6>
                                      <ul className="list-disc pl-5 space-y-1">
                                        {meds.filter(med => med !== null).map((med, idx) => (
                                          <li key={idx}>
                                            <span className="font-medium">{med.medication_name}</span> - {med.dosage}, {med.frequency} (for {med.duration_days} days)
                                          </li>
                                        ))}
                                      </ul>
                                    </div>
                                  );
                                }
                                return null;
                              })()}
                            </div>
                          </div>
                        ) : (
                          <div className="text-sm text-gray-500 italic bg-white p-4 rounded border border-gray-200 border-dashed">
                            No prescription notes available for this visit.
                          </div>
                        )}
                      </div>

                    </div>

                    {/* Download Buttons — shown for completed appointments with a prescription */}
                    {record.status === 'completed' && record.prescription_notes && (
                      <div className="mt-6 pt-5 border-t border-gray-200 flex flex-col sm:flex-row gap-3">
                        <button
                          onClick={() =>
                            downloadPdf(
                              <PrescriptionPDF record={record} />,
                              `prescription-${record.appointment_id}.pdf`
                            )
                          }
                          className="flex-1 inline-flex items-center justify-center px-4 py-2.5 bg-emerald-600 text-white rounded-lg text-sm font-medium hover:bg-emerald-700 transition-colors shadow-sm"
                        >
                          <Download className="h-4 w-4 mr-2" />
                          Download Prescription (PDF)
                        </button>
                        <button
                          onClick={async () => {
                            let payment = null;
                            try {
                              const res = await patientApi.getPaymentByAppointment(record.appointment_id);
                              payment = res.data?.data;
                            } catch { /* payment info not available */ }
                            downloadPdf(
                              <InvoicePDF record={record} payment={payment} />,
                              `invoice-${record.appointment_id}.pdf`
                            );
                          }}
                          className="flex-1 inline-flex items-center justify-center px-4 py-2.5 bg-slate-700 text-white rounded-lg text-sm font-medium hover:bg-slate-800 transition-colors shadow-sm"
                        >
                          <FileText className="h-4 w-4 mr-2" />
                          Download Invoice (PDF)
                        </button>
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </DashboardLayout>
  );
};

export default AppointmentHistory;
